spring:
  datasource:
    url: jdbc:postgresql://${application.db.host}:${application.db.port}/${application.db.name}
    username: ${application.db.user}
    password: ${application.db.password}
  jpa:
    show-sql: true
    database: postgresql
  kafka:
    bootstrap-servers: "localhost:9092"
    properties:
      schema.registry.url: http://localhost:8081
logging:
  level:
    # Log Kafka
    org.springframework.kafka.listener: DEBUG
    org.springframework.kafka.listener.adapter: INFO
server:
  port: 50003
grpc:
  server:
    port: 50013
application:
  db:
    host: localhost
    port: 5432
    name: shipping
    user: shipping
    password: shipping
