spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shipping
    username: shipping
    password: shipping
  jpa:
    show-sql: true
    database: postgresql
  kafka:
    producer:
      bootstrap-servers: "localhost:9092"
application:
  kafka:
    topic: orders
    partitions: 2
    replicationFactor: 1
    groupId: shipping
