spring:
  datasource:
    url: jdbc:postgresql://${application.db.host}:${application.db.port}/${application.db.name}
    username: ${application.db.user}
    password: ${application.db.password}
  jpa:
    show-sql: true
    database: postgresql
  kafka:
    bootstrap-servers: "local-kafka-0.local-kafka-headless.default.svc.cluster.local:9092"
    properties:
      schema.registry.url: "http://local-schema-registry.default.svc.cluster.local:8081"
logging:
  level:
    # Log Kafka
    org.springframework.kafka.listener: DEBUG
    org.springframework.kafka.listener.adapter: INFO
server:
  servlet:
    # Set context path for K8s ingress rules to match different services
    # See https://kubernetes.io/docs/concepts/services-networking/ingress/#simple-fanout
    # Otherwise, Ingress won't find services
    # See https://stackoverflow.com/questions/76061215/route-different-paths-to-different-services
    context-path: /shipping
grpc:
  server:
    port: 50013
  client:
    shipping:
      # Choose gRPC target (or connect to a gRPC server)
      # See https://yidongnan.github.io/grpc-spring-boot-starter/en/client/configuration.html#choosing-the-target
      address: static://shipping:50013
      # Disable TLS for development
      # See https://yidongnan.github.io/grpc-spring-boot-starter/en/client/security.html#disable-transport-layer-security
      negotiationType: plaintext
application:
  db:
    host: "Please set APPLICATION_DB_HOST in k8s config map"
    port: "Please set APPLICATION_DB_PORT in k8s config map"
    name: "Please set APPLICATION_DB_NAME in k8s config map"
    user: "Please set APPLICATION_DB_USER in k8s config map"
    password: "Please set APPLICATION_DB_PASSWORD in k8s config map"

