spring:
  datasource:
    url: jdbc:postgresql://${application.db.host}:${application.db.port}/${application.db.name}
    username: ${application.db.user}
    password: ${application.db.password}
  jpa:
    show-sql: true
    database: postgresql
  kafka:
    producer:
      bootstrap-servers: "localhost:9092"
logging:
  level:
    # Log Kafka
    org.springframework.kafka.listener: DEBUG
    org.springframework.kafka.listener.adapter: INFO
application:
  kafka:
    topic: orders
    partitions: 2
    replicationFactor: 1
    groupId: shipping
  db:
    host: localhost
    port: 5432
    name: shipping
    user: shipping
    password: shipping
