spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vinci
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    generate-ddl: true
