spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: order
    password: order
  jpa:
    show-sql: true
    database: postgresql
  liquibase:
    # Drop the existing to repopulate the whole database
    # drop-first: true
    # Used for development to update the changelogs continuously
    clear-checksums: true
  kafka:
    producer:
      bootstrap-servers: "localhost:9092"
logging:
  level:
    # Enable Liquibase logs for development
    liquibase.database: DEBUG
    liquibase.changelog: DEBUG
    # Log to see liquibase's SQL
    liquibase.executor.jvm.[JdbcExecutor$ExecuteStatementCallback]: DEBUG
    # Log Kafka
    org.springframework.kafka.listener: DEBUG
    org.springframework.kafka.listener.adapter: INFO
application:
  kafka:
    topic: orders
    partitions: 2
    replicationFactor: 1
    groupId: awesomeGroup
