spring:
  profiles:
    active: dev # Activate "dev" profile by default
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  liquibase:
    change-log: classpath:liquibase/master.yml
server:
  port: 50002
  tomcat:
    # Allow pipe character in URL to support passing commas such as "userId,asc"
    relaxed-query-chars: "|"