spring:
  datasource:
    url: jdbc:postgresql://${application.db.host}:${application.db.port}/${application.db.name}
    username: ${application.db.user}
    password: ${application.db.password}
  jpa:
    show-sql: true
    database: postgresql
  liquibase:
    # Drop the existing to repopulate the whole database
    # drop-first: true
    # Used for development to update the changelogs continuously
    clear-checksums: true
  kafka:
    bootstrap-servers: "localhost:9092"
    properties:
      schema.registry.url: http://localhost:8081
logging:
  level:
    # Enable Liquibase logs for development
    liquibase.database: DEBUG
    liquibase.changelog: DEBUG
    # Log to see liquibase's SQL
    liquibase.executor.jvm.[JdbcExecutor$ExecuteStatementCallback]: DEBUG
    # Log Kafka
    org.springframework.kafka.listener: DEBUG
    org.springframework.kafka.listener.adapter: INFO
server:
  port: 50002
application:
  db:
    host: localhost
    port: 5432
    name: payment
    user: payment
    password: payment
  host: localhost
  port: ${server.port}
