name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build bom
        run: mvn clean install
        working-directory: bom

      - name: Build grpc-interface
        run: mvn clean install
        working-directory: grpc-interface

      - name: Build order
        run: mvn clean install
        working-directory: order

      - name: Build payment
        run: mvn clean install
        working-directory: payment

      - name: Build shipping
        run: mvn clean install
        working-directory: shipping
